language: objective-c

script:
  - xcodebuild clean build -project DLLocalNotifications.xcodeproj -scheme DLLocalNotifications -sdk iphonesimulator
  - xcodebuild test -project DLLocalNotifications.xcodeproj -scheme "DLLocalNotifications" -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 6,OS=10.0'

osx_image: xcode8
xcode_sdk: iphonesimulator10.0
